salesforce:
  clientId: "![lgbCHDCFi6LQg5RPDhghU7qfOZgYFQJ3r+X0S1FfjMDWkh1ZF1Lr50heysPPt7yofWa0PWT9U/iD3FZqZDiTF8x4d5cp6opu8BYCmqtvtbxyhvj128ubjCH44WJZqhCS]"
  clientSecret: "![JJdiZOtReVmDrbGPxPzHfw8ope2OfCNifo113X0GhR0kE6Mx55/bqK96eAMO1V5S68j2WKDv/344A+WfvZSaXbEg1iSnzDzGKmVj/XqIbbY=]"
  username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
  password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
  token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
  new:
    username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
    password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
    token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
  int:
    username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
    password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
    token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
api:
  clientId: "![HenXznGhThPVmxMn4pfvyEiYrjrq8xqubr+ACru6OI6kACRw2AluWKUiBuVCDiuk]"
  clientSecret: "![7AI83D9je9k0oZTQyjS45pYrjFSWKgqBpWxOkSTT0ahNcVFkyOxAx46l7lysDhqj]"