salesforce:
  clientId: "![t9EoevW3Nqr32qTvs0QWhErxeymcDjjoE4uIiHK5I/333PQoewNlrcXINitm/gm4oDYPVbUsxwLXdlrY8ziLVfQkzYHvjzTXQwPkIp4VY5166jB1+aRNYwJSgrMaWriB]"
  clientSecret: "![o0bJRUhHeXzB/wE8MWc+0JvgzbGKqUnoSW4TWefYZStYj59LPaij2jhxl5cUgBT6D6Tf4gkTOYqsCJYneZ47p9A8LYhLFpyWDUUtTbDcrGw=]"
  username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
  password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
  token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
  new:
    username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
    password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
    token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
  int:
    username: "![x/yVZzUlr8Lmi9R2NN9smY6CxPYxpSUpcdJOHjT0EIF1xvieuTYpvAEx0vK0368J]"
    password: "![0QeKxEb2bc1X+qIZZi8lfr7GRIrISgcIZFjV3OedJm0=]"
    token: "![Uv4cV7Pa4YUGWjQAN3+HIA8Tk8wGxi+315mv9rZHbyA=]"
api:
  clientId: "![HenXznGhThPVmxMn4pfvyEiYrjrq8xqubr+ACru6OI6kACRw2AluWKUiBuVCDiuk]"
  clientSecret: "![7AI83D9je9k0oZTQyjS45pYrjFSWKgqBpWxOkSTT0ahNcVFkyOxAx46l7lysDhqj]"